### ISSUE TITLE
Question to "mixin" other Primes / Objects

### ISSUE THREAD

**Issue by TeilZeitMensch** [kamicane/prime#42]
Hi, 

if a create a Prime that is only used as a mixin for other primes, it seems, that "direct" variables of this prime are instantiated correctly, but variables inside an object in this prime are mixed, as they were static.

Look at these example please, to understand correctly, what i mean: 

```
var prime = require('prime');

var Counter = prime({
    counterVariable: 0,
    counterObject: {
        anotherCounterVariable: 0
    }, 
    raiseCounters: function() {
        this.counterVariable++;
        this.counterObject.anotherCounterVariable++;

        this.logCounters();
    }, 
    logCounters: function() {
        console.log('Counters', this.counterVariable, this.counterObject.anotherCounterVariable);
    }
});

var Foo = prime({
    mixin: Counter
});

var Bar = prime({
    mixin: Counter
});

var foo = new Foo();
var bar = new Bar();

foo.raiseCounters();
bar.raiseCounters();

foo.raiseCounters();
bar.raiseCounters();

```

the output in console is: 

```
Counters 1 1
Counters 1 2
Counters 2 3
Counters 2 4
```

So`counterVariable` is instantiated and mixed in correctly in the different Primes.
But `counterObject.anotherCounterVariable` stays static over the different Primes "Foo" and "Bar".

Is this a bug? Or should we tread it like an undocumentet feature? I dont think, that this is a good behaviour of Prime-mixin...

**Comment by arian** [comment]
iirc, what mixin does, is copy the properties of the prototype (basically the object you pass to `prime()`), into the new object. It does a shallow copy, so only the pointer to the `counterObject` object is copied, but both copies point to the same object. If you change the value of a property of that object, other objects pointing to the same object will see those changes too.

This behavior is intentional, keeping the implementation fast and simple, and closer to 'native' JS, rather than complexing it with lots of special behavior.

To fix this, you'll need to create a new object in the constructor method, with which the mixed-in methods can work with.
